# Generated by Django 5.1.6 on 2025-04-14 15:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_ecoimpact_date_ecoimpact_date_recorded'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='items_recycled',
            field=models.PositiveIntegerField(default=0, help_text='Number of items recycled by the user'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='items_shared',
            field=models.PositiveIntegerField(default=0, help_text='Number of items shared by the user'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_co2_saved',
            field=models.FloatField(default=0, help_text='Total CO2 saved in kg'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_waste_reduced',
            field=models.FloatField(default=0, help_text='Total waste reduced in kg'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_water_saved',
            field=models.FloatField(default=0, help_text='Total water saved in liters'),
        ),
    ]
