# Generated by Django 5.1.6 on 2025-04-15 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_product_created_at_product_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recyclableitem',
            old_name='date_created',
            new_name='submitted_at',
        ),
        migrations.RemoveField(
            model_name='recyclableitem',
            name='pickup_scheduled',
        ),
        migrations.AlterField(
            model_name='ecoimpact',
            name='co2_saved_kg',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ecoimpact',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.product'),
        ),
        migrations.AlterField(
            model_name='ecoimpact',
            name='recyclable_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.recyclableitem'),
        ),
        migrations.AlterField(
            model_name='ecoimpact',
            name='trees_saved',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ecoimpact',
            name='waste_diverted_kg',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ecoimpact',
            name='water_saved_liters',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='estimated_co2_saving',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='estimated_waste_reduction',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='estimated_water_saving',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='recyclableitem',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('good', 'Good'), ('worn', 'Worn'), ('damaged', 'Damaged')], default='good', max_length=100),
        ),
        migrations.AlterField(
            model_name='recyclableitem',
            name='estimated_co2_saving',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='recyclableitem',
            name='estimated_waste_reduction',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='recyclableitem',
            name='estimated_water_saving',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='recyclableitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recyclable_items/'),
        ),
        migrations.AlterField(
            model_name='recyclableitem',
            name='item_type',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('plastic', 'Plastic'), ('glass', 'Glass'), ('paper', 'Paper'), ('metal', 'Metal'), ('textile', 'Textile'), ('other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='items_recycled',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='items_shared',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='total_co2_saved',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='total_waste_reduced',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='total_water_saved',
            field=models.FloatField(default=0),
        ),
    ]
