# Generated by Django 5.1.6 on 2025-04-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_date_created_recyclableitem_submitted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecycleWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=20)),
                ('specialization', models.CharField(max_length=100)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
