# Generated by Django 5.1.6 on 2025-04-15 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_recycleworker'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='recycle_worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.recycleworker'),
        ),
    ]
