# Generated by Django 5.1.6 on 2025-04-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_product_recycle_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='recycleworker',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('for_sale', 'For Sale'), ('for_exchange', 'For Exchange'), ('for_donation', 'For Donation'), ('recycling', 'For Recycling')], max_length=20),
        ),
    ]
