# Generated by Django 5.1.6 on 2025-05-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_userprofile_bio_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='recycle_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('picked_up', 'Picked Up')], default='pending', max_length=20),
        ),
    ]
