# Generated by Django 5.1.6 on 2025-05-09 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_product_pickup_time_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='recycle_worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='accounts.recycleworker'),
        ),
    ]
