# Generated by Django 5.1.6 on 2025-05-09 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_product_recycle_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='recyclableitem',
            name='assigned_worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recyclable_items', to='accounts.recycleworker'),
        ),
        migrations.AddField(
            model_name='recyclableitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('collected', 'Collected')], default='pending', max_length=20),
        ),
    ]
